package com.analyfy.analify.DTO.Statistics;

import lombok.Builder;
import lombok.Data;

import java.util.Map;

@Data
@Builder
public class AnalyticsAssistantResponse {

    /**
     * Natural-language answer generated by the LLM.
     */
    private String answer;

    /**
     * Optional short summary of what data was used (filters, role, etc.).
     */
    private Map<String, Object> metadata;
}
